from ParticipantReportOBX import generate_participant_report_obx
from data_exploration import *

if __name__ == "__main__":
    # autogenerate config
    df = read_ACES_csv('obxdata.csv')
    #### CONFIG
    df['brandno'] = df['ProductNo_OBX']
    CONFIG = {
        'STUDY_NAME'                          : 'OBX-PAIN',
        # EDIT, NOT REQUIRED,
        'FEEDBACK_LINK'                       :
            'https://radiclescience.qualtrics.com/jfe/form/SV_5tKRVNxaaXr19BQ?ParticipantStudy=OBX',
        # EDIT, NOT REQUIRED
        'S3_prefix'                           :
            'https://radicle-production.s3.us-west-2.amazonaws.com/obx_pain/',
        # EDIT, REQUIRED, DEFAULT VALUE
        'NAME_COL'                            : (
            'Q2_5', 'Tell us a little bit about yourself. - First Name',
            'OBX_Eligibility Demographics and Characteristics',
            'choice', -1),
        # EDIT, REQUIRED, DEFAULT VALUE
        'COL_ZIPCODE'                         : (
            'Q6_9', 'Physical mailing address to receive your study product - zip code',
            'OBX_Eligibility Demographics and Characteristics', 'choice', -1),
        # EDIT, REQUIRED, DEFAULT VALUE
        'COL_GENDER'                          : (
            'Q91', 'What was your assigned sex at birth?', 'OBX_Eligibility Demographics and Characteristics', 'choice',
            -1),

        # EDIT, REQUIRED,  DEFAULT VALUE

        'BRAND_COL'                           : 'brandno',
        # EDIT, REQUIRED

        'EMAIL_COL'                           : (
            'Q2_7', 'Tell us a little bit about yourself. - Email', 'OBX_Eligibility Demographics and Characteristics',
            'choice', -1)
        ,
        # EDIT, REQUIRED

        'AGE_COL'                             : ('Age_OBX', 'Age_OBX', 'OBX_Health Weekly', 'choice', 21),
        # EDIT,  NOT REQUIRED, DEFAULT VALUE
        'BAR_COLOR'                           : '#7e60f5',
        'HASH_COL'                            : 'hashcode',

        # EDIT,  NOT REQUIRED
        'BRAND_MAP'                           : {
            0: 'Control Group',
            1: 'Cannafloria Sleep Drops nightly tincture',
            2: 'Hudson Hemp Sleep',
            3: 'The Mendi Co Night Tincture',
            4: 'RealSleep',
            5: 'Straight Hemp CBD Oil',
            6: 'CURE Sleep',
            7: 'Trokie Nighttime CBD Rapid Relief Tabs',
            8: 'Rest by Vitaldiol',
            9: 'TheraOne Sleep CBD Tincture',
            },
        # EDIT,  REQUIRED
        'STUDY_CONDITIONS'                    : [ 'pain', 'qol', 'anxiety', 'sleep',],

        # EDIT,  NOT REQUIRED, POPULATE BASED ON 'STUDY_CONDITIONS' FOR DEFAULT VALUES
        'STUDY_CONDITION_TO_STR'              : {
            'anxiety': 'Anxiety',
            'sleep'  : 'Sleep Difficulties',
            'pain'   : 'Pain',
            'qol'    : 'Quality of Life',

            },
        # EDIT,  NOT REQUIRED, POPULATE BASED ON 'STUDY_CONDITIONS' FOR DEFAULT VALUES
        'STUDY_CONDITION_TO_SCORE'            : {
            'qol'    : 'Kemp',
            'anxiety': 'PROMIS Anxiety 4a',
            'sleep'  : 'PROMIS SLEEP 8b',
            'pain'   : 'PEG',
            },

        #  HIDDEN INTERNAL FIELD, DEFAULT VALUES NULL
        'STUDY_CONDITION_TO_SURVEY_COMLPETION': {
            'qol'    : None,
            'anxiety': None,
            'sleep'  : None,
            'pain'   : None,
            },

        # EDIT,  REQUIRED
        'conditions'                          :
            [
                ('AnxietyCondition_OBX', 'AnxietyCondition_OBX', 'OBX_Eligibility Demographics and Characteristics',
                 'choice', -1),
                ('SleepCondition_OBX', 'SleepCondition_OBX', 'OBX_Eligibility Demographics and Characteristics',
                 'choice', -1),
                ('PainCondition_OBX', 'PainCondition_OBX', 'OBX_Eligibility Demographics and Characteristics', 'choice',
                 -1)
                ],
        # AUTOGENERATED, READ-ONLY, will look like 'conditions' field
        # 'completed_all_surveys_daily'         :
        #     generate_tuple_list_days(('Finished', 'Finished'), df, ),
        'completed_all_surveys_weekly'        :
            [
                ('Finished', 'Finished', 'OBX_Baseline', 'choice', 7),
                ('Finished', 'Finished', 'OBX_Health Weekly', 'choice', 14),
                ('Finished', 'Finished', 'OBX_Health Weekly', 'choice', 21),
                ('Finished', 'Finished', 'OBX_Health Weekly', 'choice', 28),
                ('Finished', 'Finished', 'OBX_Health Weekly', 'choice', 35),
                ],
        'all_weeklies_without_baseline'       :
            [
                ('Finished', 'Finished', 'OBX_Health Weekly', 'choice', 14),
                ('Finished', 'Finished', 'OBX_Health Weekly', 'choice', 21),
                ('Finished', 'Finished', 'OBX_Health Weekly', 'choice', 28),
                ('Finished', 'Finished', 'OBX_Health Weekly', 'choice', 35),
                ]
        }

    CONFIG['STUDY_CONDITION_TO_TEXT'] = {
        'wellbeing'          : {
            'text_baseline': f'Wellbeing was measured on a scale of 0-25, with higher scores representing higher ' \
                             'levels of wellbeing.  At the beginning of the study, your wellbeing score  was {} the '
                             'average wellbeing score among all participantsin our '
                             'control group',
            'text_scores'  : 'You experienced {' \
                             'text_scores_input_1} in your wellbeing score, indicating that your wellbeing {' \
                             'text_scores_input_2} throughout the study.',

            },
        'qol'                : {
            'text_baseline': f'Quality of life was measured on a scale of 1-7, with higher scores representing better '
                             f'' \
                             'quality of life. At the beginning of the study, your quality of life score  was {} than '
                             'the average quality of life score among all participants ' \
                             'in our control group.',
            'text_scores'  : 'You experienced {' \
                             'text_scores_input_1} in your quality of life score, indicating that your quality of '
                             'life {' \
                             'text_scores_input_2} throughout the study.',
            },
        'anxiety'            : {
            'text_baseline': f'Anxiety was measured on a scale of 0-21, with higher scores representing higher ' \
                             'levels of anxiety. At the beginning of the study, your anxiety score  was {} the '
                             'average anxiety score among all participants in our '
                             'control group.',
            'text_scores'  : 'You experienced {' \
                             'text_scores_input_1} in your anxiety score, indicating that your anxiety {' \
                             'text_scores_input_2} throughout the study.',

            },
        'sleep'              : {
            'text_baseline': f'Sleep disturbance was measured on a scale of 8-40, with higher scores representing ' \
                             'higher levels of sleep disturbance. At the beginning of the study, your sleep ' \
                             'disturbance score was {} the average sleep disturbance ' \
                             'score among all participants in our control group.',
            'text_scores'  : 'You experienced {' \
                             'text_scores_input_1} in your sleep disturbance score, indicating that your sleep ' \
                             'quality {text_scores_input_2} throughout the study.',

            },
        'pain'               : {
            'text_baseline': f'Pain was measured on a scale of 0-10, with higher scores representing higher levels ' \
                             'of pain.  At the beginning of the study, your pain score was '
                             '{' \
                             '} the average pain score among all participants in our control group .',
            'text_scores'  : 'You experienced {text_scores_input_1} in your pain score, ' \
                             'indicating that your pain {text_scores_input_2} throughout the study.',
            },
        'general_information': {
            'intro_text' : '',
            'text_gender': 'Participants were recruited from across the United States, with the greatest number of '
                           'participants residing in California and Florida.',
            'text_age'   : 'Participant ages ranged from %d to %d. The average age of participants was around %d '
                           'years.',
            },

        }

    CONFIG['condition_minmax'] = {
        'qol'    : (1, 7),
        'anxiety': (0, 21),
        'sleep'  : (8, 40),
        'pain'   : (0, 10),
        }
    # contacts = pd.read_csv('contacts.csv')
    contacts = None
    generate_participant_report_obx(df, CONFIG, contacts)

